---
- hosts: ek_role_manager
  run_once: true

  tasks:
  - name: 'Checking component_path and stack_name parameters'
    assert:
      that:
      - component_path is defined
      - stack_name is defined

  - set_fact:
      ek_stack_dir: "/tmp/ek-{{ stack_name }}-{{ lookup('pipe','date') | to_uuid }}"

  - name: "Deploying {{ stack_name }} stack"
    block:
    - name: "Ensure that temporary directory {{ ek_stack_dir }} exists"
      file:
        path: "{{ ek_stack_dir }}"
        state: directory
        mode: 0777

    - name: "Sending component files on a Docker Swarm manager"
      copy:
        src: "{{ component_path }}/"
        dest: "{{ ek_stack_dir }}/"

    - name: "Checking if docker-compose.yml file exists"
      stat:
        path: "{{ ek_stack_dir }}/docker-compose.yml"
      register: compose_yml

    - name: "Executing stack deploy using docker-compose.yml"
      when: compose_yml.stat.exists == true
      become: true
      docker_stack:
        state: present
        name: "{{ stack_name }}"
        compose: "{{ ek_stack_dir }}/docker-compose.yml"

    - block:
      - name: "Checking if docker-compose.yaml file exists"
        stat:
          path: "{{ ek_stack_dir }}/docker-compose.yaml"
        register: compose_yaml

      - name: "Executing stack deploy using docker-compose.yaml"
        when: compose_yaml.stat.exists == true
        become: true
        docker_stack:
          state: present
          name: "{{ stack_name }}"
          compose: "{{ ek_stack_dir }}/docker-compose.yaml"
      when: compose_yml.stat.exists == false

    always:
    - name: "Purge temporary directory"
      file:
        path: "{{ ek_stack_dir }}"
        state: absent
