---
- hosts: nodes
  gather_facts: false
  pre_tasks:
  - name: Load configuration
    include_role:
      name: ekara.configuration
  tasks:
  - name: Define proxy if needed
    set_fact:
      ekara_proxy: "{{ekara_configuration_params.proxy | default({})}}"
  - name: Install Ansible packages
    include_role:
      name: ekara.ansible_install
    vars:
      ekara_install_proxy: "{{ekara_proxy}}"
  - block:
    - name: Set devices to mount
      set_fact:
        ekara_devices: "{{item.devices}}"
      loop: "{{ekara_configuration_params.volumes}}"
      loop_control:
        label: "{{item.name}}"
      when:
      - item.name == inventory_hostname
    - name: Mount FS for disks
      include_role:
        name: ekara.filesystem
      vars:
        ekara_fs_dev: "{{item.device}}"
        ekara_fs_mount: "{{item.volume}}"
      loop: "{{ekara_devices}}"
      loop_control:
        label: "{{item.volume}}"
    when:
    - ekara_configuration_params.volumes is defined
  - name: Define custom variables
    set_fact:
      ekara_nodes_ips: "{{ groups['managers'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | join(',') }}"
  - name: Install Docker
    include_role:
      name: ekara.docker
    vars:
      ekara_docker_proxy: "{{ekara_proxy}}"
      ekara_docker_params: "{{ekara_configuration_params.orchestrator.docker.params}}"
      ekara_docker_ca_cn: "{{ekara_configuration_params.environment.name}}_{{ekara_configuration_params.environment.uid}}"
      ekara_docker_provider: "{{ekara_provider_map}}"
      ekara_docker_all: "{{ekara_configuration_params.orchestrator.docker}}"
      ekara_docker_nodes_ip: "{{hostvars[groups['managers'][0]].ekara_nodes_ips}}"

- name: Install Swarm
  import_playbook: install_swarm.yml
