---
- src: https://github.com/lagoon-platform/ansible-role-configuration.git
  version: alpha1
  name: lagoon.configuration

- src: https://github.com/lagoon-platform/ansible-role-install.git
  version: alpha2
  name: lagoon.ansible_install

- src: https://github.com/tbouvet/ansible-role-docker.git
  version: fix-group
  name: lagoon.docker

- src: https://github.com/lagoon-platform/ansible-role-filesystem.git
  version: alpha1
  name: lagoon.filesystem
