---
- src: https://github.com/ekara-platform/ansible-role-configuration.git
  version: alpha4
  name: ekara.configuration

- src: https://github.com/ekara-platform/ansible-role-install.git
  version: master
  name: ekara.ansible_install

- src: https://github.com/ekara-platform/ansible-role-docker.git
  version: master
  name: ekara.docker

- src: https://github.com/ekara-platform/ansible-role-filesystem.git
  version: alpha4
  name: ekara.filesystem
