---
- src: https://github.com/ekara-platform/ansible-role-configuration.git
  version: v1.0.0
  name: ekara.configuration

- src: https://github.com/ekara-platform/ansible-role-install.git
  version: v1.0.0
  name: ekara.install

- src: https://github.com/ekara-platform/ansible-role-docker.git
  version: v1.0.0
  name: ekara.docker
